=== bradik/ResumeBuilder/src/main/resources/cv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://bradik.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Contents" type="ContentsType"/>
  <xs:complexType name="ContentsType">
    <xs:sequence>
      <xs:element type="PersonalType" name="Personal"/>
      <xs:element type="PositionType" name="Position"/>
      <xs:element type="ExperiencesType" name="Experiences"/>
      <xs:element type="Key-skillsType" name="Key-skills"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExperiencesType">
    <xs:sequence>
      <xs:element type="ExperienceType" name="Experience"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AddressLocalityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="address"/>
        <xs:attribute type="xs:string" name="metro"/>
        <xs:attribute type="xs:string" name="info" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Key-skillsType">
    <xs:sequence>
      <xs:element name="Skill" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Java"/>
            <xs:enumeration value="C++"/>
            <xs:enumeration value="SQL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PersonalType">
    <xs:sequence>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="AddressLocalityType" name="AddressLocality" />
      <xs:element type="xs:string" name="Telephone"/>
      <xs:element type="xs:string" name="Email"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="gender"/>
    <xs:attribute type="xs:string" name="birthDate"/>
  </xs:complexType>
  <xs:complexType name="PositionType">
    <xs:sequence>
      <xs:element type="xs:string" name="Category"/>
      <xs:element type="xs:string" name="Specialization"/>
      <xs:element type="xs:string" name="Workload"/>
      <xs:element type="xs:string" name="Schedule"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>
  <xs:complexType name="Experience-positionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ExperienceType">
    <xs:sequence>
      <xs:element type="Experience-positionType" name="Experience-position"/>
      <xs:element type="xs:string" name="Experience-description"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="start"/>
    <xs:attribute type="xs:string" name="title"/>
    <xs:attribute type="xs:string" name="url"/>
  </xs:complexType>
</xs:schema>

=== bradik/ResumeBuilder/src/main/resources/cv.xml
<Contents xmlns="http://bradik.com"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://bradik.com cv.xsd">
    <Personal gender="Мужчина" birthDate="1975-12-04">
        <Name>Яковлев Родион Владимирович</Name>
        <AddressLocality address="Санкт-Петербург" metro="м. Ладожская" info=", готов к переезду, готов к командировкам"></AddressLocality>
        <Telephone>+79119765740</Telephone>
        <Email>bradnm@ya.ru</Email>
    </Personal>

    <Position name="java developer">
        <Category>Информационные технологии, интернет, телеком</Category>
        <Specialization>Программирование, Разработка</Specialization>
        <Workload>Занятость: полная занятость, частичная занятость, проектная работа</Workload>
        <Schedule>График работы: полный день</Schedule>
    </Position>

    <Experiences>
        <Experience start="Июнь 2017" title="TOPJAVA" url="javaops.ru">
            <Experience-position name="Программист"/>
            <Experience-description>
                Участие в разработке Spring/JPA Enterprise приложения c авторизацией и правами доступа на основе ролей
                на стеке: Maven, Spring MVC, Spring Security, REST (Jackson), Java 8 Stream API:
                * реализация сохранения в базы Postgres и HSQLDB на основе Spring JBDC, JPA(Hibernate) и Spring-Data-JPA
                * реализация и JUnit тестирование REST и AJAX контроллеров
                * реализация клиента на Bootstrap (css/js), datatables, jQuery + plugins.
            </Experience-description>
        </Experience>
    </Experiences>

    <Key-skills>
        <Skill>Java</Skill>
        <Skill>C++</Skill>
        <Skill>SQL</Skill>
        <Skill>Java</Skill>
    </Key-skills>

</Contents>
